/**
 * BEFAS BES fonlari seed listesi — TAM LISTE (400 fon).
 * Kaynak: EGM emakin fon kunyesi platformu (https://emeklilik.egm.org.tr/fon-kunyesi-anasayfa)
 * Manuel guncelleme tarihi: 2026-09-13
 *
 * NAV/getiri yok — sadece meta (kod + isim + kurucu + kategori + tip).
 * Kullanici fiyat gormek istiyorsa BEFAS fon detay sayfasina yonlendirilir.
 */

export interface BesSeedFund {
  code: string;
  name: string;
  founder: string;
  besKategori: string;
  tip: 'BES' | 'OKS' | 'DK';
}

export const BES_SEED: BesSeedFund[] = [
  { code: 'AAJ', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'ABE', name: 'S&P 500 YABANCI BYF FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'ACV', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'AEA', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'AEB', name: 'HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AEC', name: 'UNİLEVER BİRİNCİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'AEH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AEI', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'AEK', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AEN', name: 'ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AEP', name: 'UNİLEVER İKİNCİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'AER', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'AET', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'AEU', name: 'BIST TEMETTÜ ENDEKSİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'AEY', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Viennalife Emeklilik ve Hayat A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'AEZ', name: 'YAPI KREDİ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'AE1', name: 'BİRİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'AE2', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AE3', name: 'DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Dinamik Değişken Fon', tip: 'BES' },
  { code: 'AFH', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'AFJ', name: 'OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Temkinli Değişken Fon', tip: 'OKS' },
  { code: 'AFP', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'AGA', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'AGB', name: 'BÜYÜME KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'AGD', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'AGE', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'AGG', name: 'KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'AGH', name: 'KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AGM', name: 'MUHAFAZAKAR KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'AGT', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'AG1', name: 'İKİNCİ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AG2', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AG3', name: 'HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AG4', name: 'TEMKİNLİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Temkinli Değişken Fon', tip: 'BES' },
  { code: 'AHB', name: 'İKİNCİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AHC', name: 'ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AHJ', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'AHL', name: 'AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Agresif Değişken Fon', tip: 'BES' },
  { code: 'AH1', name: 'İKİNCİ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AH2', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'AH3', name: 'BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AH4', name: 'İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AH5', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AH6', name: 'BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'AH8', name: 'KARMA EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'AH9', name: 'ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Atak Değişken Fon', tip: 'BES' },
  { code: 'AIE', name: 'OKS BÜYÜME KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Büyüme Katılım Değişken Fon', tip: 'OKS' },
  { code: 'AIP', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'AJA', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'AJB', name: 'OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Atak Değişken Fon', tip: 'OKS' },
  { code: 'AJC', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'AJF', name: 'OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Temkinli Değişken Fon', tip: 'OKS' },
  { code: 'AJG', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'AJH', name: 'OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'OKS Atak Katılım Değişken Fon', tip: 'OKS' },
  { code: 'AJP', name: 'OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Atak Değişken Fon', tip: 'OKS' },
  { code: 'AJR', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'AJT', name: 'OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Temkinli Değişken Fon', tip: 'OKS' },
  { code: 'AJV', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'AJY', name: 'OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Atak Katılım Değişken Fon', tip: 'OKS' },
  { code: 'AJZ', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'ALI', name: 'KOÇ İŞTİRAK ENDEKSİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'ALJ', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'ALR', name: 'KARMA EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'ALS', name: 'DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'ALU', name: 'KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'ALZ', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'AMF', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'AMG', name: 'BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AMR', name: 'KAMU DIŞ BORÇLANMA ARAÇLARI (ABD DOLARI 0-5 YIL VADELİ) EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AMY', name: 'KARMA GRUP EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'AMZ', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'ANE', name: 'KARMA EMEKLİLİK YATIRIM FONU', founder: 'Viennalife Emeklilik ve Hayat A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'ANG', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Viennalife Emeklilik ve Hayat A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'ANJ', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'ANK', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Viennalife Emeklilik ve Hayat A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'ANP', name: 'OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Dinamik Değişken Fon', tip: 'OKS' },
  { code: 'ANS', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Viennalife Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AO1', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'AO2', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'APG', name: 'YENİLENEBİLİR ENERJİ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'ATE', name: 'İŞ BANKASI İŞTİRAK ENDEKSİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'ATK', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'AUA', name: 'FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'AUG', name: 'İKİNCİ KARMA EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'AVB', name: 'KAMU DIŞ BORÇLANMA ARAÇLARI (ABD DOLARI 5-15 YIL VADELİ) EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AVD', name: 'KARMA EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'AVG', name: 'DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AVJ', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'AVN', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'AVO', name: 'ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AVR', name: 'TEKNOLOJİ SEKTÖRÜ YABANCI DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'AYJ', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'AZA', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AZD', name: 'BİRİNCİ KARMA EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'AZH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'AZK', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'AZL', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'AZS', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'AZY', name: 'TARIM VE GIDA FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'BAE', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BBD', name: 'BIST30 DIŞI ŞİRKETLER HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'BBH', name: 'HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'BEE', name: 'DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'BEF', name: 'OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Dinamik Katılım Değişken Fon', tip: 'OKS' },
  { code: 'BEH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'BEI', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'BEK', name: 'FİBA PORTFÖY BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BEO', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'BGE', name: 'DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'BGK', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BGL', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'BHK', name: 'KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Kira Sertifikası Katılım Fonu', tip: 'BES' },
  { code: 'BHS', name: 'SÜRDÜRÜLEBİLİRLİK HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'BHT', name: 'TEKNOLOJİ SEKTÖRÜ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'BKB', name: 'KAMU DIŞ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BNA', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'BNB', name: 'MUTLAK GETİRİ HEDEFLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'BNK', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'BNL', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'BNO', name: 'TEMETTÜ ÖDEYEN ŞİRKETLER HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'BNS', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'BNZ', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'BPC', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'BPE', name: 'DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'BPF', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BPG', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BPH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'BPI', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'BPJ', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'BPK', name: 'İKİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI (ABD DOLARI 0-5 YIL VADELİ) EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BPL', name: 'BİRİNCİ PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'BPN', name: 'OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Dinamik Değişken Fon', tip: 'OKS' },
  { code: 'BPO', name: 'OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Dinamik Katılım Değişken Fon', tip: 'OKS' },
  { code: 'BPR', name: 'OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Muhafazakar Değişken Fon', tip: 'OKS' },
  { code: 'BPS', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'BPU', name: 'BİRİNCİ KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'BSR', name: 'SÜRDÜRÜLEBİLİRLİK FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'BZY', name: 'TEKNOLOJİ SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'CFA', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'CFB', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'CFC', name: 'ORTA VADELİ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'CFD', name: 'DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'CFE', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'CFK', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'CFY', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'CGE', name: 'DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'CGG', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'CHA', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'CHC', name: 'OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Muhafazakar Değişken Fon', tip: 'OKS' },
  { code: 'CHD', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'CHG', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'CHH', name: 'BİRİNCİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'CHI', name: 'OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Dinamik Katılım Değişken Fon', tip: 'OKS' },
  { code: 'CHK', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'CHL', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'CHM', name: 'DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Dinamik Değişken Fon', tip: 'BES' },
  { code: 'CHN', name: 'DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'CHO', name: 'OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Atak Değişken Fon', tip: 'OKS' },
  { code: 'CHS', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'CHT', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'CHU', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'QNB Sağlık Hayat Sigorta ve Emeklilik A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'EAE', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'EHG', name: 'OYAK PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'EHK', name: 'KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'EIE', name: 'ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Atak Değişken Fon', tip: 'BES' },
  { code: 'EIF', name: 'OYAK PORTFÖY KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'EIG', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'EIH', name: 'OYAK PORTFÖY HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'EIK', name: 'DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'EMI', name: 'EMLAK SEKTÖRÜ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'EMY', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'ENF', name: 'ENERJİ SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'EST', name: 'OYAK PORTFÖY STANDART EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'FEA', name: 'ATLAS PORTFÖY ÖZEL SEKTÖR BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'FEF', name: 'TACİRLER PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'FEI', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'FEN', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'FEO', name: 'DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Dinamik Değişken Fon', tip: 'BES' },
  { code: 'FER', name: 'DEĞIŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'FES', name: 'TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Temkinli Değişken Fon', tip: 'BES' },
  { code: 'FET', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'FFC', name: 'TEKNOLOJİ SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'FFZ', name: 'INVEO PORTFÖY FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'FGF', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'FGH', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'FIC', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'FIE', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'FIF', name: 'İSTANBUL PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'FIG', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'FIH', name: 'OKS ATAK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Atak Değişken Fon', tip: 'OKS' },
  { code: 'FII', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'FIK', name: 'FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'FIM', name: 'KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'FIR', name: 'OSMANLI PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'FIS', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'FIU', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'FIV', name: 'OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Atak Katılım Değişken Fon', tip: 'OKS' },
  { code: 'FIY', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'FIZ', name: 'OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Muhafazakar Değişken Fon', tip: 'OKS' },
  { code: 'FJG', name: 'RE-PIE PORTFÖY DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'FOA', name: 'AZİMUT FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'FVI', name: 'ESG SÜRDÜRÜLEBİLİRLİK FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'FYL', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'FYN', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'FYU', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'FYY', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'GCK', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'GCN', name: 'YENİ TEKNOLOJİLER HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'GCS', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'GCT', name: 'BİRİNCİ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'GCV', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'GCY', name: 'KARMA EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'GDV', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'GEA', name: 'KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'GED', name: 'TEMETTÜ ÖDEYEN ŞİRKETLER HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'GEF', name: 'DİNAMİK DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Dinamik Değişken Fon', tip: 'BES' },
  { code: 'GEG', name: 'HİSSE SENEDİ GRUP EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'GEH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'GEK', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'GEL', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'GES', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'GEU', name: 'DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'GEV', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'GFH', name: 'SÜRDÜRÜLEBİLİRLİK HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'GGJ', name: 'GÜMÜŞ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Gümüş Fonu', tip: 'BES' },
  { code: 'GHA', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'GHD', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'GHE', name: 'DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Dinamik Değişken Fon', tip: 'BES' },
  { code: 'GHF', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'GHG', name: 'DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'GHH', name: 'SÜRDÜRÜLEBİLİRLİK HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'GHI', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'GHJ', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'GHK', name: 'DIŞ BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'GHL', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'GHM', name: 'OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Dinamik Değişken Fon', tip: 'OKS' },
  { code: 'GHN', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'GHO', name: 'ÜÇÜNCÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'GHP', name: 'OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Temkinli Değişken Fon', tip: 'OKS' },
  { code: 'GHT', name: 'DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'GHU', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'GHV', name: 'OKS DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Dengeli Katılım Değişken Fon', tip: 'OKS' },
  { code: 'GHY', name: 'OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Dinamik Katılım Değişken Fon', tip: 'OKS' },
  { code: 'GHZ', name: 'OKS TEMKİNLİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Temkinli Katılım Değişken Fon', tip: 'OKS' },
  { code: 'GKB', name: 'KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Kira Sertifikası Katılım Fonu', tip: 'BES' },
  { code: 'GMF', name: 'GÜMÜŞ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Gümüş Fonu', tip: 'BES' },
  { code: 'GRA', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'HEA', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'HEB', name: 'DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'HEC', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'HED', name: 'KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'HEE', name: 'KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'HEG', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'HEI', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'HEK', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'HEL', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'HEP', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'HER', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'HES', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'HET', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'HFS', name: 'HSBC FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Hayat ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'HHB', name: 'BIST-30 DIŞI ŞİRKETLER HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'HHM', name: 'TEKNOLOJİ SEKTÖRÜ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'HHY', name: 'KARMA EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'HSR', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'HS1', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'IEA', name: 'DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'IEB', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'IEE', name: 'DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'IEF', name: 'DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Dinamik Değişken Fon', tip: 'BES' },
  { code: 'IEG', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'IEH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'IEK', name: 'KARMA EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Karma Fon', tip: 'BES' },
  { code: 'IER', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'IGE', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'KEA', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'KEB', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'KED', name: 'GENÇLERE YÖNELİK ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'KEF', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'KEG', name: 'DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'KEH', name: 'KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'KEK', name: 'KATILIM DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'KES', name: 'AGRESİF KATILIM DEĞİŞKEN (DÖVİZ) EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'KET', name: 'OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Atak Katılım Değişken Fon', tip: 'OKS' },
  { code: 'KEY', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'KEZ', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'KFE', name: 'KUVEYT TÜRK KATILIM FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Fon Sepeti', tip: 'BES' },
  { code: 'KGC', name: 'GÜMÜŞ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Gümüş Katılım Fonu', tip: 'BES' },
  { code: 'KHL', name: 'KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'KJM', name: 'KIYMETLİ MADENLER KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'KKS', name: 'KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Kira Sertifikası Katılım Fonu', tip: 'BES' },
  { code: 'KKV', name: 'KISA VADELİ KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Kira Sertifikası Katılım Fonu', tip: 'BES' },
  { code: 'KLT', name: 'TEMETTÜ ÖDEYEN ŞİRKETLER KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'KLV', name: 'KATILIM KARMA EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Karma Fon', tip: 'BES' },
  { code: 'KML', name: 'KIYMETLİ MADENLER EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'KMP', name: 'KIYMETLİ MADENLER EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'KOA', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'KOE', name: 'KOÇ HOLDİNG EMEKLİ VAKFI BİRİNCİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'KOS', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'KRM', name: 'KATILIM KARMA EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Karma Fon', tip: 'BES' },
  { code: 'KRU', name: 'KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Kira Sertifikası Katılım Fonu', tip: 'BES' },
  { code: 'KSH', name: 'TEKNOLOJİ SEKTÖRÜ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'KSU', name: 'SÜRDÜRÜLEBİLİRLİK KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'KTZ', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Katılım Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'MDD', name: 'MERKEZİ ALACAĞIN DEVRİ DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'MDE', name: 'MERKEZİ ALACAĞIN DEVRİ TEMKİNLİ DEĞİŞKEN EYF', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Temkinli Değişken Fon', tip: 'BES' },
  { code: 'MDK', name: 'MERKEZİ ALACAĞIN DEVRİ MUHAFAZAKAR KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'MEA', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'MEB', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'MEV', name: 'TEKNOLOJİ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'MEY', name: 'SÜRDÜRÜLEBİLİRLİK FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'MHA', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'MHB', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'MHC', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'MHD', name: 'KAMU DIŞ BORÇLANMA ARAÇLARI (ABD DOLARI 0-5 YIL VADELİ) EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'MHE', name: 'MUTLAK GETİRİ HEDEFLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'MHG', name: 'BORÇLANMA ARAÇLARI GRUP EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'MHH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'MHI', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'MHK', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'MHL', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'MHM', name: 'OKS TEMKİNLİ DEGİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Temkinli Değişken Fon', tip: 'OKS' },
  { code: 'MHN', name: 'OKS DENGELİ DEGİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'MHO', name: 'OKS ATAK DEGİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Atak Değişken Fon', tip: 'OKS' },
  { code: 'MHR', name: 'OKS AGRESİF DEGİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'MHS', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'MHT', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'MHU', name: 'OKS ATAK KATILIM DEGİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Atak Katılım Değişken Fon', tip: 'OKS' },
  { code: 'MHV', name: 'OKS AGRESİF KATILIM DEGİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'MHY', name: 'DENGELİ DEĞİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'MHZ', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'Metlife Emeklilik ve Hayat A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'MZL', name: 'İKİNCİ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'MZN', name: 'BİRİNCİ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'MZP', name: 'ÜÇÜNCÜ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'NHA', name: 'ALTIN EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Altın Fonu', tip: 'BES' },
  { code: 'NHM', name: 'TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Temkinli Değişken Fon', tip: 'BES' },
  { code: 'NHN', name: 'İKİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Zurich Yaşam ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'NZA', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'PRC', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'PRS', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'BNP Paribas Cardif Emeklilik A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'RZM', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'RZN', name: 'FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'AXA Hayat ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'SBA', name: 'SABANCI TOPLULUĞU ŞİRKETLERİ ENDEKSİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'SSH', name: 'SANAYİ ŞİRKETLERİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'HDI Fiba Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'TBJ', name: 'TEKNOLOJİ SEKTÖRÜ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'THE', name: 'TARIM VE GIDA FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'THK', name: 'KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Kira Sertifikası Katılım Fonu', tip: 'BES' },
  { code: 'TJY', name: 'ÜÇÜNCÜ YAŞAM DÖNGÜSÜ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Yaşam Döngüsü Fonu', tip: 'BES' },
  { code: 'TKV', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Bereket Emeklilik ve Hayat A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'TML', name: 'BİRİNCİ YAŞAM DÖNGÜSÜ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Yaşam Döngüsü Fonu', tip: 'BES' },
  { code: 'TMN', name: 'MERKEZİ ALACAĞIN DEVRİ DENGELİ KATILIM DEĞİŞKEN EYF', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Değişken Fon', tip: 'BES' },
  { code: 'TNE', name: 'TEMİZ ENERJİ SEKTÖRÜ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Garanti Emeklilik ve Hayat A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'TSZ', name: 'TAŞINMAZ VE İNŞAAT SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'TVC', name: 'TARIM VE GIDA SEKTÖRÜ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'TVG', name: 'TARIM VE GIDA FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Anadolu Hayat Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'TVH', name: 'TEKNOLOJİ ŞİRKETLERİ HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'TYJ', name: 'İKİNCİ YAŞAM DÖNGÜSÜ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Yaşam Döngüsü Fonu', tip: 'BES' },
  { code: 'VEB', name: 'KATILIM DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'VED', name: 'OKS MUHAFAZAKAR KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Muhafazakar Katılım Değişken Fon', tip: 'OKS' },
  { code: 'VEG', name: 'BİRİNCİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'VEH', name: 'HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'VEI', name: 'KATKI EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Katkı Fonu', tip: 'DK' },
  { code: 'VEK', name: 'STANDART EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Standart Fon', tip: 'BES' },
  { code: 'VEL', name: 'PARA PİYASASI EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Para Piyasası Fonu', tip: 'BES' },
  { code: 'VEO', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'VEP', name: 'OKS TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Temkinli Değişken Fon', tip: 'OKS' },
  { code: 'VER', name: 'KATILIM KATKI EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Katkı Fonu', tip: 'DK' },
  { code: 'VES', name: 'BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'VET', name: 'KAMU DIŞ BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Kamu Dış Borçlanma Araçları Fonu', tip: 'BES' },
  { code: 'VEU', name: 'TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Temkinli Değişken Fon', tip: 'BES' },
  { code: 'VEV', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'VEY', name: 'PARA PİYASASI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Para Piyasası Katılım Fonu', tip: 'BES' },
  { code: 'VGA', name: 'ALTIN KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Altın Katılım Fonu', tip: 'BES' },
  { code: 'VGB', name: 'KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Standart Fon', tip: 'BES' },
  { code: 'VGC', name: 'OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Dinamik Değişken Fon', tip: 'OKS' },
  { code: 'VGD', name: 'KIYMETLİ MADENLER KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'VGE', name: 'GÜMÜŞ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Gümüş Katılım Fonu', tip: 'BES' },
  { code: 'VGF', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'VGG', name: 'OKS DENGELİ KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Dengeli Katılım Değişken Fon', tip: 'OKS' },
  { code: 'VGH', name: 'OKS ATAK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Atak Katılım Değişken Fon', tip: 'OKS' },
  { code: 'VGK', name: 'OKS KATILIM STANDART EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Katılım Standart Fon', tip: 'OKS' },
  { code: 'VGP', name: 'TURKCELL GRUBU ÇALIŞANLARINA YÖNELİK PERA 1 DEGİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'VGT', name: 'PERA 2 DEGİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'VGY', name: 'PERA 3 DEGİŞKEN GRUP EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Değişken Fon', tip: 'BES' },
  { code: 'VGZ', name: 'OKS STANDART EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Standart Fon', tip: 'OKS' },
  { code: 'VKE', name: 'BAŞLANGIÇ KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Başlangıç Katılım Fon', tip: 'OKS' },
  { code: 'VKJ', name: 'BAŞLANGIÇ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Başlangıç Fon', tip: 'OKS' },
  { code: 'VVA', name: 'OKS AGRESİF DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Değişken Fon', tip: 'OKS' },
  { code: 'VVD', name: 'OKS DİNAMİK DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Dinamik Değişken Fon', tip: 'OKS' },
  { code: 'VVE', name: 'OKS DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Dengeli Değişken Fon', tip: 'OKS' },
  { code: 'VVM', name: 'OKS MUHAFAZAKAR DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Muhafazakar Değişken Fon', tip: 'OKS' },
  { code: 'VVU', name: 'OKS DİNAMİK KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Dinamik Katılım Değişken Fon', tip: 'OKS' },
  { code: 'VVZ', name: 'OKS AGRESİF KATILIM DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Agesa Hayat ve Emeklilik A.Ş.', besKategori: 'OKS Agresif Katılım Değişken Fon', tip: 'OKS' },
  { code: 'VYB', name: 'KATILIM HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Hisse Senedi Fonu', tip: 'BES' },
  { code: 'YZD', name: 'TEKNOLOJİ SEKTÖRÜ FON SEPETİ EMEKLİLİK YATIRIM FONU', founder: 'Allianz Yaşam ve Emeklilik A.Ş.', besKategori: 'Fon Sepeti', tip: 'BES' },
  { code: 'ZHB', name: 'SÜRDÜRÜLEBİLİRLİK HİSSE SENEDİ EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Hisse Senedi Fonu', tip: 'BES' },
  { code: 'ZHD', name: 'KAMU DIŞ KİRA SERTİFİKALARI KATILIM EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Kira Sertifikası Katılım Fonu', tip: 'BES' },
  { code: 'ZHE', name: 'DENGELİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Dengeli Değişken Fon', tip: 'BES' },
  { code: 'ZHF', name: 'KATILIM TEMKİNLİ DEĞİŞKEN EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Katılım Temkinli Değişken Fon', tip: 'BES' },
  { code: 'ZHG', name: 'KAMU BORÇLANMA ARAÇLARI EMEKLİLİK YATIRIM FONU', founder: 'Türkiye Hayat ve Emeklilik A.Ş.', besKategori: 'Borçlanma Araçları Fonu', tip: 'BES' },
];
